language: android
jdk: oraclejdk8
before_install:
 - chmod +x gradlew

android:
  components:
    - tools
    - platform-tools
    - build-tools-24.0.1
    - android-24
    - extra-android-support
    - extra-android-m2repository
    - extra-google-m2repository